name: Build React Native App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android emulator
      uses: crazy-max/ghaction-android-emulator@v2
      with:
        api-level: 30
        target: default
        arch: x86
        profile: default

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Start Emulator
      run: emulator -avd <nome_do_seu_avd>

    - name: Build and test
      run: |
        npx react-native run-android

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-app
        path: android/app/build/outputs
