name: React Native Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/checkout@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install Android tools
        run: sdkmanager "tools" "platform-tools"

      - name: Create emulator
        run: echo no | avdmanager create avd -n test -d "pixel" -k "system-images;android-30;google_apis;x86" --force

      - name: Start emulator
        run: emulator -avd test -no-audio -no-window

      - name: Wait for emulator
        run: adb wait-for-device

      - name: Build and test
        run: npx react-native run-android
