name: React Native Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: '31'

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install emulator dependencies
        run: sdkmanager "emulator" "system-images;android-31;google_apis;x86"

      - name: Create and start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          profile: Nexus_5X_API_31

      - name: Wait for emulator
        run: adb wait-for-device

      - name: Build and test
        run: npx react-native run-android
